name: booksforall
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"
 
dependencies:
  d_button: ^0.0.10
  d_info: ^0.2.0
  d_method: ^0.2.3
  d_session: ^0.0.2
  d_view: ^0.0.5
  dartz: ^0.10.1
  extended_image: ^8.2.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  gap: ^3.0.1
  get: ^4.6.6
  google_fonts: ^6.1.0
  http: ^1.1.2
  intl: ^0.19.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
